### ISSUE TITLE
Добавить меч культистов 

### ISSUE THREAD

**Issue by The-Vi-X** [sch1zk/Imperial-Space-SS14#14]
К сожалению перевода нет, но воть 
[cult_sword.zip](https://github.com/sch1zk/Imperial-Space-SS14/files/10296842/cult_sword.zip)

**Comment by sch1zk** [comment]
Научись пользоваться Git. Если сомневаешься в своих силах - скачай GitHub Desktop.
Я понимаю, что тебе проще взваливать эту всю работу на меня, но раз ты уже начал разбираться в Simple Code части, будь добр, запили Pull request со всеми необходимыми изменениями.
