### ISSUE TITLE
Moose map RP issue

### ISSUE THREAD

**Issue by DeRybik** [sch1zk/Imperial-Space-SS14#5]
### Описание

На карте добавили число модулей ДАМ и теперь можно собрать ДАМ с количеством ядер больше чем одно.
Изначально легенда карты предполагала что станция должна продержаться на одном ядре и солярах пока РнД что то не придумает.
Теперь это не так и станции комфортно.
О легенде напоминает вот этот маленький клочок бумаги в инжинерке под ДАМ. Текст на английском, но все же.

Не то чтобы я адовый РП задрот но шизик попросил оформить это как issue. Ну и пожалста.

### Скриншоты

![image](https://user-images.githubusercontent.com/46026896/206024732-f142fe45-97c0-4c19-a3be-802c609cb5ab.png)

**Comment by sch1zk** [comment]
Убрал этот листочек, ибо он просто уведомляет инженеров о перебоях с поставками.
Если будет необходимо, просто добавлю другой листок с немного иной информацией, а пока обойдемся настолько радикальным методом.
